(function () {
    console.log('AI Automation Recorder: Content script initialized on', window.location.href);

    // Check if we should be recording or at least indicate activity
    chrome.storage.local.get(['recordingState'], (result) => {
        console.log('Current recording state:', result.recordingState);
    });

    document.addEventListener('click', (event) => {
        handleEvent(event, 'click');
    }, true);

    document.addEventListener('input', (event) => {
        // We only want to record input once it's finished or throttled
        // But for MVP, let's just record it
        handleEvent(event, 'input');
    });

    document.addEventListener('change', (event) => {
        if (event.target.tagName === 'SELECT') {
            handleEvent(event, 'change');
        }
    });

    function getPageState() {
        return {
            title: document.title,
            url: window.location.href,
            // Capture a summary of visible text to detect changes (alerts, success messages)
            visibleText: document.body.innerText.substring(0, 1000).replace(/\s+/g, ' ')
        };
    }

    function handleEvent(event, type) {
        // Immediate check for recording state and logging
        chrome.storage.local.get(['recordingState'], (result) => {
            if (result.recordingState !== 'recording') return;

            console.log(`[AI Recorder] Event detected: ${type}`, event.target);

            const target = event.target;
            const preState = getPageState();

            // --- NEW: Capture locators IMMEDIATELY before any delay ---
            // This prevents issues if the element disappears or changes during the delay
            const immediateLocators = extractLocators(target);

            // 500ms delay to capture the "Post-action" state change (e.g. success message)
            setTimeout(() => {
                const postState = getPageState();
                const eventData = {
                    type: type,
                    timestamp: Date.now(),
                    url: window.location.href,
                    value: target.value || target.innerText || '',
                    locators: immediateLocators,
                    stateChange: {
                        pre: preState,
                        post: postState
                    }
                };

                console.log('[AI Recorder] Sending event to background:', eventData);

                if (!chrome.runtime || !chrome.runtime.id) {
                    console.warn('[AI Recorder] Extension disconnected.');
                    return;
                }

                try {
                    chrome.runtime.sendMessage({ action: 'recordEvent', event: eventData });
                } catch (error) {
                    console.error('[AI Recorder] Send error:', error);
                }
            }, 500);
        });
    }

    // Listen for validation requests from background
    chrome.runtime.onMessage.addListener((message, sender, sendResponse) => {
        if (message.action === 'validateXPath') {
            const count = validateXPath(message.xpath);
            sendResponse({ matchCount: count });
        }
        return true; // Keep channel open for async response
    });

    function validateXPath(xpath) {
        try {
            const result = document.evaluate(xpath, document, null, XPathResult.ORDERED_NODE_SNAPSHOT_TYPE, null);
            return result.snapshotLength;
        } catch (e) {
            console.error('Invalid XPath generated by AI:', xpath, e);
            return 0;
        }
    }

    function isDynamicId(id) {
        if (!id || typeof id !== 'string') return true;
        // User provided regex: (ht_|rc-|[0-9a-f]{6,})
        const dynamicIdPattern = /(ht_|rc-|[0-9a-f]{6,})/i;
        return dynamicIdPattern.test(id);
    }

    function sanitizeHtmlForAi(html) {
        if (!html) return '';
        // Use a simple regex-based sanitization to avoid full DOM parsing if possible,
        // but for complex HTML, we'll strip 'id="..."' specifically if they are dynamic.
        return html.replace(/id=["']([^"']+)["']/g, (match, id) => {
            return isDynamicId(id) ? '' : match;
        }).replace(/class=["']([^"']+)["']/g, (match, cls) => {
            // Strip common framework classes that clutter context
            const cleanClasses = cls.split(/\s+/).filter(c => !/^(ant-|rc-|ext-)/.test(c)).join(' ');
            return cleanClasses ? `class="${cleanClasses}"` : '';
        });
    }

    function extractLocators(element) {
        const locators = {};
        const candidates = [];

        // --- Rule 3: Priority Locator Types ---

        // 🥇 1. Text (Exact and Normalized)
        const text = element.innerText?.trim();
        if (text && text.length < 50 && text.length > 0 && !/\d{3,}/.test(text)) {
            candidates.push(`//*[normalize-space()='${text.replace(/'/g, "\\'")}']`);
        }

        // 🥈 2. ARIA Label / Role / Title
        const ariaLabel = element.getAttribute('aria-label');
        if (ariaLabel) {
            candidates.push(`//*[@aria-label='${ariaLabel.replace(/'/g, "\\'")}']`);
        }
        const title = element.getAttribute('title');
        if (title) {
            candidates.push(`//*[@title='${title.replace(/'/g, "\\'")}']`);
        }

        // 🥉 3. Label -> Target Relation (XPath Axes)
        const labelText = findLabelText(element);
        if (labelText) {
            candidates.push(`//label[normalize-space()='${labelText}']/following::${element.tagName.toLowerCase()}[1]`);
            candidates.push(`//label[contains(normalize-space(), '${labelText}')]/following::${element.tagName.toLowerCase()}[1]`);
        }

        // 🟢 4. Data Attributes (data-testid, etc)
        const dataAttrs = ['data-test', 'data-testid', 'data-cy', 'data-qa'];
        for (const attr of dataAttrs) {
            const val = element.getAttribute(attr);
            if (val) {
                candidates.push(`//*[@${attr}='${val}']`);
                locators.dataTest = val;
                break;
            }
        }

        // 🟡 5. Basic Attributes (Filtered for Dynamic IDs)
        if (element.id && !isDynamicId(element.id)) {
            locators.id = element.id;
            candidates.push(`//*[@id='${element.id}']`);
        }
        if (element.name) {
            locators.name = element.name;
            candidates.push(`//*[@name='${element.name}']`);
        }

        // ⚠️ 6. Class (Only if semantic/stable)
        if (element.className && typeof element.className === 'string') {
            const cleanClasses = element.className.split(/\s+/).filter(c => !/^(ant-|rc-|ext-|ht_)/.test(c));
            if (cleanClasses.length > 0) {
                candidates.push(`//${element.tagName.toLowerCase()}[contains(@class, '${cleanClasses[0]}')]`);
            }
        }

        // 7. Structural Fallback (Rule 1 & 4)
        locators.xpath = getRelativeXPath(element);
        if (locators.xpath) {
            const divisions = locators.xpath.split('/').length;
            const indices = (locators.xpath.match(/\[\d+\]/g) || []).length;
            const startsWithBad = locators.xpath.startsWith('/html/body') || locators.xpath.startsWith('//*[@id="app"]');

            // Rule 1 & 4: Max 3 divisions (4 parts), Max 1 index, No full DOM paths
            if (!startsWithBad && divisions <= 4 && indices <= 1) {
                candidates.push(locators.xpath);
            }
        }

        // 5. Enriched Context for AI (Sanitized)
        const context = {
            elementHtml: sanitizeHtmlForAi(element.outerHTML.substring(0, 800)),
            parentHtml: element.parentElement ? sanitizeHtmlForAi(element.parentElement.outerHTML.substring(0, 800)) : '',
            closestLabel: labelText,
            ancestorHeading: findAncestorHeading(element),
            role: element.getAttribute('role') || element.tagName.toLowerCase(),
            candidates: Array.from(new Set(candidates))
        };

        return { ...locators, aiContext: context };
    }


    function findAncestorHeading(element) {
        let curr = element;
        while (curr && curr !== document.body) {
            // Check siblings for headings first (common in sections)
            const prev = curr.previousElementSibling;
            if (prev && /H[1-6]/.test(prev.tagName)) return prev.innerText.trim();

            // Move to parent
            curr = curr.parentElement;
            if (curr) {
                const heading = curr.querySelector('h1, h2, h3, h4');
                if (heading) return heading.innerText.trim();
            }
        }
        return '';
    }

    function getCssSelector(el) {
        if (!(el instanceof Element)) return '';
        const path = [];
        while (el.nodeType === Node.ELEMENT_NODE) {
            let selector = el.nodeName.toLowerCase();
            if (el.id) {
                selector += '#' + el.id;
                path.unshift(selector);
                break;
            } else {
                let sib = el, nth = 1;
                while (sib = sib.previousElementSibling) {
                    if (sib.nodeName.toLowerCase() == selector) nth++;
                }
                if (nth != 1) selector += ":nth-of-type(" + nth + ")";
            }
            path.unshift(selector);
            el = el.parentNode;
        }
        return path.join(" > ");
    }

    function getRelativeXPath(element) {
        // 1. Try Unique ID
        if (element.id && isUnique(`//*[@id='${element.id}']`)) {
            return `//*[@id='${element.id}']`;
        }

        // 2. Try Unique Name
        if (element.name && isUnique(`//*[@name='${element.name}']`)) {
            return `//*[@name='${element.name}']`;
        }

        // 3. Try Text Content (Exact Match) - Good for Buttons/Links
        const text = element.innerText?.trim();
        if (text && text.length < 20 && text.length > 0) {
            const textPath = `//*[text()='${text}']`;
            if (isUnique(textPath)) return textPath;

            // Try containing text
            const containsPath = `//*[contains(text(), '${text}')]`;
            if (isUnique(containsPath)) return containsPath;
        }

        // 4. Try Data Attributes (data-test, data-cy, etc.)
        const dataAttrs = ['data-test', 'data-testid', 'data-cy', 'data-qa', 'placeholder', 'title', 'aria-label', 'alt'];
        for (const attr of dataAttrs) {
            const val = element.getAttribute(attr);
            if (val) {
                const attrPath = `//*[@${attr}='${val}']`;
                if (isUnique(attrPath)) return attrPath;
            }
        }

        // 5. Class Name (Combined) - Be careful with multiple classes
        if (element.className && typeof element.className === 'string') {
            const classes = element.className.split(/\s+/).filter(c => c.length > 0);
            if (classes.length > 0) {
                // Try first distinct class
                for (let cls of classes) {
                    const classPath = `//*[contains(@class, '${cls}')]`;
                    if (isUnique(classPath)) return classPath;
                }
            }
        }

        // 6. Relative Axes: Label -> Input
        // Find preceding label
        if (element.tagName === 'INPUT' || element.tagName === 'TEXTAREA' || element.tagName === 'SELECT') {
            const labelPath = `//label[text()='${findLabelText(element)}']/following-sibling::${element.tagName.toLowerCase()}`;
            if (isUnique(labelPath)) return labelPath;
        }

        // 7. Fallback: Absolute XPath
        return getAbsoluteXPath(element);
    }

    function findLabelText(element) {
        // Simple heuristic to find a preceding label or parent label
        // This is a placeholder for more complex label logic
        return '';
    }

    function isUnique(xpath) {
        try {
            const result = document.evaluate(xpath, document, null, XPathResult.ORDERED_NODE_SNAPSHOT_TYPE, null);
            return result.snapshotLength === 1;
        } catch (e) {
            return false;
        }
    }

    function getAbsoluteXPath(element) {
        if (element.id !== '') {
            return `//*[@id="${element.id}"]`;
        }
        if (element === document.body) {
            return '/html/body';
        }

        let ix = 0;
        const siblings = element.parentNode.childNodes;
        for (let i = 0; i < siblings.length; i++) {
            const sibling = siblings[i];
            if (sibling === element) {
                return getAbsoluteXPath(element.parentNode) + '/' + element.tagName.toLowerCase() + '[' + (ix + 1) + ']';
            }
            if (sibling.nodeType === 1 && sibling.tagName === element.tagName) {
                ix++;
            }
        }
    }

})();
